create table if not exists ratings_mpa
(
    id          int generated by default as identity primary key,
    name        varchar(100) not null unique
);

create table if not exists films
(
    id           int generated by default as identity primary key,
    name         varchar(100) not null,
    description  varchar(200),
    release_date date         not null,
    duration     int          not null,
    rating_id    int          not null references ratings_mpa (id) on delete restrict
);

create table if not exists genres
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique
);

create table if not exists film_genres
(
    film_id  int references films (id) on delete cascade,
    genre_id int references genres (id) on delete restrict,
    primary key (film_id, genre_id)
);

create table if not exists users
(
    id       int generated by default as identity primary key,
    email    varchar(100) not null,
    login    varchar(100) not null,
    name     varchar(100),
    birthday date
);

create table if not exists film_likes
(
    film_id  int references films (id) on delete cascade,
    user_id int references users (id) on delete cascade,
    primary key (film_id, user_id)
);

create table if not exists friends
(
    user_id int references users (id) on delete cascade,
    friend_id int references users (id) on delete cascade
);